foodoor/food_door/bag/urls.py
from django.urls import path
from . import views
app_name='bag'
urlpatterns=[
    path('add/<int:item_id>/',views.add_bag,name='add_bag'),
    path('',views.bag_detail,name='bag_detail'),
    path('remove/<int:item_id>/',views.bag_remove,name='bag_remove'),
    path('full_remove/<int:item_id>/',views.full_remove,name='full_remove'),
]

foodoor/food_door/food_door/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from foodoorapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name='home'),
    path('',include('foodoorapp.urls')),
    path('bag/', include('bag.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodoor/food_door/foodoorapp/urls.py
from django.urls import path
from . import views
app_name ='foodoorapp'
urlpatterns=[
    path('',views.allItmCat,name='allItmCat'),
    path('<slug:c_slug>/',views.allItmCat,name='items_by_category'),
    path('<slug:c_slug>/<slug:item_slug>/',views.ItemCatDetail,name='ItemCatDetail'),
]

foodoor/food_door/bag/models.py
from django.db import models
from foodoorapp.models import Item
# Create your models here.
class Bag(models.Model):
    bag_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Bag'
        ordering=['date_added']
    def __str__(self):
        return self.bag_id
class BagItem(models.Model):
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    bag=models.ForeignKey(Bag,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='BagItem'

    def sub_total(self):
        return self.item.price*self.quantity
    def __str__(self):
        return self.item

foodoor/food_door/foodoorapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('foodoorapp:items_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Item(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='item',blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now=True)
    update=models.DateTimeField(auto_now=True)
    class Meta:
        ordering=('name',)
        verbose_name='item'
        verbose_name_plural='items'

    def get_url(self):
        return reverse('foodoorapp:ItemCatDetail',args=[self.category.slug,self.slug])
    def __str__(self):
        return '{}'.format(self.name)

foodoor/food_door/bag/views.py
from django.shortcuts import render, redirect, get_object_or_404
from foodoorapp.models import Item
from .models import Bag,BagItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _bag_id(request):
    bag=request.session.session_key
    if not bag:
        bag=request.session.create()
    return  bag
def add_bag(request,item_id):
    item=Item.objects.get(id=item_id)
    try:
        bag=Bag.objects.get(bag_id=_bag_id(request))
    except Bag.DoesNotExist:
        bag=Bag.objects.create(bag_id=_bag_id(request))
        bag.save()
    try:
        bag_item=BagItem.objects.get(item=item,bag=bag)
        if bag_item.quantity < bag_item.item.stock:
            bag_item.quantity +=1
        bag_item.save();
    except BagItem.DoesNotExist:
        bag_item=BagItem.objects.create(
            item=item,
            quantity=1,
            bag=bag
        )
        bag_item.save()
    return redirect('bag:bag_detail')
def bag_detail(request,total=0,counter=0,bag_items=None):
    try:
        bbag=Bag.objects.get(bag_id=_bag_id(request))
        bag_items=BagItem.objects.filter(bag=bag,active=True)
        for bag_item in bag_items:
            total +=(bag_item.item.price * bag_item.quantity)
            counter += bag_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'bag.html',dict(bag_items=bag_items,total=total,counter=counter))

def bag_remove(request,item_id):
    bag = Bag.objects.get(bag_id=_bag_id(request))
    item=get_object_or_404(Item,id=item_id)
    bag_item=BagItem.objects.get(item=item,bag=bag)
    if bag_item.quantity>1:
        bag_item.quantity-=1
        bag_item.save()
    else:
        bag_item.delete()
    return redirect('bag:bag_detail')
def full_remove(request,item_id):
    bag = Bag.objects.get(bag_id=_bag_id(request))
    item = get_object_or_404(Item, id=item_id)
    bag_item = BagItem.objects.get(item=item, bag=bag)
    bag_item.delete()
    return redirect('bag:bag_detail')

foodoor/food_door/foodoorapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
from.models import Category,Item


# def home(request):
#     return HttpResponse('hrllo')
def allItmCat(request,c_slug=None,):
    c_page = None
    items_list = None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug,)
        items_list=Item.objects.filter(category=c_page,available=True)
    else:
        items_list=Item.objects.all().filter(available=True)
    paginator=Paginator(items_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        items=paginator.page(page)
    except(EmptyPage,InvalidPage):
        items=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'items':items})

def ItemCatDetail(request,c_slug,item_slug):
    try:
        item=Item.objects.get(category__slug=c_slug,slug=item_slug)
    except Exception as e:
        raise e
    return render(request,'item.html',{'item':item})

foodoor/food_door/templates/bag.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Welcome to the Food@door where you can find all needables .

{% endblock %}
{% block title %}
    Bag - Ordered Items!!!
{% endblock %}
{% block content %}
{% if not bag_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                Your Bag is empty :(
            </h1>
            <br>
            <p class="text-center">
                Please click <a href="{% url 'foodoorapp:allItmCat' %}"> Here</a>
            </p>
        </div>
    </div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="tecxt-center my_title">
            Your Bag
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for bag_item in bag_items %}
            <tr>
                <td>
                    <a href="bag_item.item.get_absolute_url"><img src={{bag_item.item.image.url}} class="float-left rounded custom_image" style="width:50px;height:50px;"></a>
                </td>
                <td class="text-left">
                    {{bag_item.item.name}}
                    <br>
                    DEL: {{bag_item.item.id}}
                    <br>
                    Unit price :{{bag_item.item.price}}
                    QTY: {{bag_item.quantity}} x ₹ {{bag_item.item.price}}
                </td>
                <td>₹ {{bag_item.sub_total}}</td>
                {% if bag_item.quantity < bag_item.item.stock %}
                <td>
                    <a href="{% url 'bag:add_bag' bag_item.item.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'bag:bag_remove' bag_item.item.id %}" class="custom_icon"><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'bag:full_remove' bag_item.item.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'bag:bag_remove' bag_item.item.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'bag:full_remove' bag_item.item.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Make sure to review selected items before proceeding the payment.
                </td>
            </tr>
            <tr>
            <td class="text-left">
                Total Amount <strong> ₹ {{total}}</strong>
            </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'foodoorapp:allItmCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
</div>
    </div>
</div><br>
{% endif %}
{% endblock %}

foodoor/food_door/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
    <div>
        {% include 'nav.html' %}
        {% include 'header.html' %}


        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

foodoor/food_door/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.desc |truncatewords:155}}
    {% else %}
        Welcome to foodoor where you find your fav foods .
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}}-Food bag
    {% else %}
        find yours food
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'foodoorapp:allItmCat' %}">Todays Special </a>{{category.name}}</p>
            </div>
        </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
    {% else %}
        <div>
            <center><img class="my_image my_image_padding" src="{% static 'img/bgn.png' %}" style="width:2000px;" alt=""></center>
        </div><br>
        <div>
            <h1 class="text-center my_title"> Todays SpecIal</h1>
            <p class="text-justify">You can find your favourite items form your nearest and shops you like the most.</p>
        </div>
    {% endif %}
        <div class="container">
            <div class="mx-auto">
                {% for item in items.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="width: 18rem;">
                        <a href="{{item.get_url}}"><img class="card-img-top my_image" src="{{ item.image.url }}" alt="{{item.name}}" style="width:250px;height:250px;"></a>
                        <div class="card-body">
                            <h4> {{item.name}}</h4>
                            <p>₹ {{item.price}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="mx-auto">
                <div class="text-center">
                    {% for pg in items.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if items.number == pg %} activate {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

foodoor/food_door/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer" >
    <p align="center">&copy; This is Foodoor</p>
</div>

foodoor/food_door/templates/header.html
{% load static %}
<div>
    <center>
        <img src="{% static 'img/crop.png' %}" alt="this is foodoor">
    </center>
</div>

foodoor/food_door/templates/item.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{item.desc|truncatewords:155}}
{% endblock %}
{% block title %}
    {{item.name}}-food@door
{% endblock %}
{% block content %}
<div class="row my_itm_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'foodoorapp:allItmCat' %}">Home</a> |<a href="{{item.category.get_url}}">{{item.name}}</a></p>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width:18rem;">
                <img src="{{item.image.url}}" alt="{{item.name}}">
                </div>
            </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_itm_title"> {{item.name}}</h1>
                <p>₹ {{item.price}}</p>
                <p class="my_title">Item spec</p>
                <p class="text-justify my_itm_text">{{item.desc}}</p>
                {% if Item.stock <= 0 %}
                    <p class="text-justify my_itm_text"><b>Not Available</b></p>
                {% else %}
                    <a class="btn btn-secondary" href="">Add To bag </a>
                {% endif %}
            </div>
        </div>
            </div>
    </div>
</div>
  {% endblock %}

foodoor/food_door/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<!--  <a class="navbar-brand" href="#">Navbar</a>-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Items
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'foodoorapp:allItmCat' %}">All items</a>
            {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
          {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="bag:bag_details" ><i class="fas fa-cart-plus">{{item_count}}</i></a>
        </li>
          {% endif %}

        <li class="nav-item">
          <a class="nav-link active" href="#"><i class="fas fa-shopping-bag"></i></a>
        </li>
      </ul>

    </div>
</nav>
<!--<nav>-->
<!--    <ul>-->
<!--        <li><a href="{% url 'foodoorapp:allItmCat' %}">All Items</a></li>-->
<!--      {% for cat in links %}-->
<!--          <li><a href="{{cat.get_url}}">{{cat.name}}</a> </li>-->

<!--        {% endfor %}-->
<!--        <li>Your Bag</li>-->
<!--    </ul>-->
<!--</nav>-->